= Shop
Matt Nicholls <transientvariable@gmail.com>
:experimental: true
:keywords: Java,Reactive,Micronaut,Quarkus,GraalVM,Microservices,Serverless
:icons: font
:iconfont-cdn: //stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
:sectanchors: true
:source-highlighter: prettify


ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Simple client and server applications that simulate a shopping cart for kicking the tires on the-state-of-the-art Java microservice frameworks. The server is built using link:https://micronaut.io/[Micronaut]. The client uses the new link:https://openjdk.java.net/groups/net/httpclient/[HTTP Client] library introduced in Java 11.

NOTE: Orginally, the scaffolding for the server was generated using the link:https://github.com/jhipster/generator-jhipster-micronaut[JHipster generator for Micronaut], but opted to take off the training wheels and use vanilla Micronaut.

== Build and Execution

=== Prerequisites

- The link:https://git-scm.com/[Git] version management tool
- The link:https://jdk.java.net/11/[Java Development Kit (JDK)], version 11 or later

=== Fetch the Source

....
$ git clone https://github.com/2speed/shop.git
$ cd shop
....

=== Server

Navigate to the `shop-server` directory and use the Gradle `run` task to start the server:
....
$ ./gradlew run
....

Output similar to the following should be displayed:
[source,bash]
----
> Task :run
12:42:01.779 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 846ms. Server Running: http://localhost:8080
<==========---> 80% EXECUTING [4s]
> :run
----

Check that the server is up and running by navigating to the endpoint `localhost:8080/metrics` via web browser or command-line application (e.g. cURL). The example below uses link:https://httpie.org/[HTTPie]:

[source,bash]
----
$ http localhost:8080/metrics
----

which should output the list of metrics than can be queried for the server:

[source,bash]
----
{
  "names": [
    "executor",
    "executor.active",
    "executor.completed",
    "executor.pool.size",
    "executor.queue.remaining",
    "executor.queued",
    "jvm.buffer.count",
    "jvm.buffer.memory.used",

    ...

    "process.files.max",
    "process.files.open",
    "process.start.time",
    "process.uptime",
    "system.cpu.count",
    "system.cpu.usage",
    "system.load.average.1m"
  ]
}
----

Individual metrics can be retrieved by appending the name of the metric to the `metrics` endpoint. For example, `localhost:8080/metrics/jvm.buffer.memory.used`.

TIP: Keyboard shortcut kbd:[Ctrl + C] can be used to stop the server.

=== Client

With the server still running, navigate to the `shop-client` directory and use the Gradle `run` task to execute the client:
....
$ ./gradlew run
....

NOTE: The requests sent by the `shop-client` are defined in the link:shop-client/src/main/resources/requests.json[] file.

Unless the default requests defined in `src/main/resources/requests.json` has been modfied, output exactly like the following will be displayed:

[source,text]
----
RECEIPT
Date: 06/11/2020
Time: 16:28:44
---------------------------------------------------------------------
Name      Quantity   Total Price
coconut   10000      $7,500.00
orange    12         $5.40
banana    35         $39.38
---------------------------------------------------------------------
          Total:     $7,544.78

----

[TIP]
====
Metrics for the requests sent to the client can be retrived from the server using the `metrics/http.server.requests` endpoint:

[source,bash]
----
$ http localhost:8080/metrics/http.server.requests

HTTP/1.1 200 OK
Date: Tue, 16 Jun 2020 21:03:34 GMT
connection: keep-alive
content-length: 574
content-type: application/json

{
  "name" : "http.server.requests",
  "measurements" : [ {
    "statistic" : "COUNT",
    "value" : 12.0
  }, {
    "statistic" : "TOTAL_TIME",
    "value" : 156.19343699999996
  }, {
    "statistic" : "MAX",
    "value" : 0.0
  } ],
  "availableTags" : [ {
    "tag" : "exception",
    "values" : [ "none" ]
  }, {
    "tag" : "method",
    "values" : [ "DELETE", "POST", "PUT", "GET" ]
  }, {
    "tag" : "uri",
    "values" : [ "/cart/receipt", "/cart", "/metrics/{name}", "/cart/{name}" ]
  }, {
    "tag" : "status",
    "values" : [ "400", "200", "201" ]
  } ]
}

----
====

=== Notes

==== General

* Initially started out with https://quarkus.io/[Quarkus] for implementing the server, but hit a hard wall when attempting use the HTTP session for state management.
    ** Quarkus does not provide support for HTTP sessions _out-of-the-box_ and the workarounds are quite hacky at the moment  ¯\_(ツ)_/¯

==== Developer Experience/Ergonomics

* Building a native binary using Micronaut with GraalVM is currently quite a daunting task, especially when compared to Quarkus
    ** Took a while to figure out exactly how to build the damn thing, however as with all things, YMMV
* Ramp up time to being productive with Micronaut is similar to that of Spring and Quarkus
    ** Even more so when using JHipster; the framework being used is almost transparent
    ** Using some of the more esoteric features like reactive streams is where things get interesting  ಠ‿ಠ
* For Spring veterans, transitioning to Micronaut might be a more _familiar_ experience
    ** Quarkus too to a degree, but it is definitely not batteries included like Spring and Micronaut - which is basically the point of a microservice right?

==== Brainstorming/TODOs

* http://rsocket.io/[RSocket] versions of the client and server?  ᕦ(ò_óˇ)ᕤ
* Deployment of server as a serverless application on Cloudflare or AWS
* Comparing the DevEx of building native binaries of the server between GraalVM and WebAssembly
    ** Possibly a Rust version of the server using Actix compiled to WASM as a control? 🤔
* Performance comparison between a native binary of the server built with GraalVM and WebAssembly
