---
micronaut:
  application.name: shop-server
  metrics.enabled: true
  health.monitor.enabled: false

---
redis:
  uri: redis://localhost

---
jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false
